
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Nov 09 11:31:50 CET 2009
//----------------------------------------------------

package conditionningTreatement;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STAR = 5;
  public static final int EOL = 3;
  public static final int TEXT = 2;
  public static final int error = 1;
  public static final int SLASH = 4;
  public static final int EOF = 0;
}

