/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.scoping;

import org.xtext.example.mydsl.scoping.AbstractFmlScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FmlScopeProvider extends AbstractFmlScopeProvider {
}
