/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import org.xtext.example.mydsl.idea.lang.FmlLanguage;

public class FmlBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public FmlBaseColorSettingsPage() {
		FmlLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return FmlLanguage.INSTANCE.getDisplayName();
	}
}
