/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.fml.ui.internal.FmlActivator;

public class FmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FmlActivator.getInstance().getInjector("org.xtext.example.mydsl.Fml");
	}

}
