//Generated by FAMILIAR
hbt : [Business] [CoreLion5] [Platform] :: _hbt ;

CoreLion5 : [Cache] [EntityMatic] [Formulator] [TaskManager] [AutomatedProcesses] [OfficeHelper] [SecurityLion] [Notification] [Commons] UIDataTableExporter* [DigitalSignature] [Facelets] [Historic] [Audit] FileCommons* :: _CoreLion5 ;

EntityMatic : GroupingEM ActionListenerEM FilterEM NamingEM :: _EntityMatic ;

GroupingEM : Single
| Multiple ;

Formulator : Debugging Execution :: _Formulator ;

AutomatedProcesses : CronSupport :: _AutomatedProcesses ;

OfficeHelper : [WebConfigurationOH] TableFilling :: _OfficeHelper ;

Notification : AttachedFiles WordLetters TargetAddress :: _Notification ;

AttachedFiles : Normal
| Compressed ;

TargetAddress : AppOwned
| Alternative ;

Commons : JPA1
| JPA2 ;

UIDataTableExporter : UIDTEPDF
| UIDTEXLS ;

DigitalSignature : EvidenceStorage SendingType Validation :: _DigitalSignature ;

SendingType : Detached
| Attached ;

Validation : Application PublicKey ValidityCRL CertifyingEntityValidity RevokedCertificate CertificateValidity :: _Validation ;

Historic : QueryHistoric :: _Historic ;

Audit : QueryAudit :: _Audit ;

FileCommons : LineGroupingFP ValidatorFP ProcessorFP FileTypeFP [WebConfigurationFP] ActionListenerFP :: FileProcessing
| ActionListenerFG LineGroupingFG CompressedFG FormatProcessorFG [WebConfigurationFG] FileTypeFG+ EncryptedFG :: FileGenerator ;

ProcessorFP : Default
| Sequence ;

FileTypeFP : [ProcTXT] [ProcXLS] :: _FileTypeFP ;

FormatProcessorFG : SequenceFG DefaultFG :: _FormatProcessorFG ;

FileTypeFG : TXTFG
| PDFFG
| XLSFG ;

TXTFG : SeparatorFG
| PositionFG ;

Platform : DataBase [Clustering] [JavaFramework] OperatingSystem+ [CachePlatform] ApplicationServer Security Deployment :: _Platform ;

DataBase : Oracle
| SQLServer
| PostgreSQL
| MySQL ;

Oracle : O10g
| O11g ;

SQLServer : V2005
| V2008 ;

JavaFramework : [Hibernate] [SEAM] :: _JavaFramework ;

Hibernate : Hibernate4
| Hibernate36 ;

SEAM : SEAM22
| SEAM21 ;

OperatingSystem : AIX
| MacOS
| Windows
| Unix
| Linux ;

Windows : Vista
| Server
| XP
| NT
| Seven ;

ApplicationServer : Websphere
| Weblogic
| JBoss ;

JBoss : JB7
| JB6
| JB510GA
| JB432GA ;

Security : SecurityApplication
| SecurityCoreLion ;

%%

FileProcessing implies not JB6 ;
FileProcessing implies Commons ;
FileProcessing implies not JB510GA ;
Notification implies not JB510GA ;
Notification implies Commons ;
Formulator implies not Weblogic ;
WordLetters implies OfficeHelper ;
OfficeHelper implies not Weblogic ;
WebConfigurationFG implies Facelets ;
Historic implies Commons ;
UIDataTableExporter implies not JB510GA ;
Commons implies not JB6 ;
SecurityLion implies Facelets ;
UIDataTableExporter implies not Websphere ;
EntityMatic implies Facelets ;
DigitalSignature implies not Weblogic ;
SecurityLion implies Commons ;
Audit implies not Websphere ;
TaskManager implies Facelets ;
Audit implies Commons ;
Formulator implies not JB510GA ;
DigitalSignature implies Commons ;
DigitalSignature implies not Websphere ;
Commons implies not JB510GA ;
AutomatedProcesses implies not JB510GA ;
WebConfigurationFP implies Facelets ;
Formulator implies Commons ;
OfficeHelper implies not JB6 ;
UIDataTableExporter implies Commons ;
Notification implies Facelets ;
TaskManager implies Commons ;
EntityMatic implies not Weblogic ;
DigitalSignature implies not JB510GA ;
OfficeHelper implies not JB510GA ;
UIDataTableExporter implies not JB6 ;
EntityMatic implies not JB510GA ;
Audit implies not Weblogic ;
FileProcessing implies not Weblogic ;
WebConfigurationOH implies Facelets ;
OfficeHelper implies Commons ;
Audit implies not JB6 ;
AutomatedProcesses implies Commons ;
Notification implies not Weblogic ;
AutomatedProcesses implies not Weblogic ;
Historic implies not Websphere ;
Commons implies not Weblogic ;
FileGenerator implies not JB6 ;
EntityMatic implies Commons ;
FileGenerator implies not Weblogic ;
Historic implies not JB6 ;
Historic implies not Weblogic ;
UIDataTableExporter implies not Weblogic ;
AutomatedProcesses implies not JB6 ;
FileGenerator implies not JB510GA ;
DigitalSignature implies not JB6 ;
Cache implies Commons ;
Facelets implies SEAM22 ;
EntityMatic implies not JB6 ;
FileGenerator implies Commons ;
Facelets implies Commons ;