/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea;

import com.google.inject.Injector;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries;
import org.xtext.example.mydsl.idea.FmlStandaloneSetupIdea;

@SuppressWarnings("all")
public class FmlIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    Injector _xblockexpression = null;
    {
      EcoreGlobalRegistries.ensureInitialized();
      FmlStandaloneSetupIdea _fmlStandaloneSetupIdea = new FmlStandaloneSetupIdea();
      _xblockexpression = _fmlStandaloneSetupIdea.createInjector();
    }
    return _xblockexpression;
  }
}
