
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 14 11:12:09 CET 2012
//----------------------------------------------------

package be.ac.fundp.info.TVLParser.Parser;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int XORAGG = 52;
  public static final int EXCLUDES = 56;
  public static final int DIVIDE = 43;
  public static final int ABS = 53;
  public static final int ALLOF = 20;
  public static final int CONST = 16;
  public static final int SHARED = 6;
  public static final int EQUALS = 34;
  public static final int BRAEND = 62;
  public static final int UMINUS = 41;
  public static final int IFANDONLYIF = 29;
  public static final int LOWER = 36;
  public static final int INTEGER = 3;
  public static final int GREATER = 35;
  public static final int INT = 10;
  public static final int REQUIRES = 57;
  public static final int IFIN = 14;
  public static final int MINUS = 40;
  public static final int DATA = 69;
  public static final int SEMICOLON = 68;
  public static final int CBRAEND = 64;
  public static final int IS = 55;
  public static final int NOT = 30;
  public static final int AND = 25;
  public static final int SOMEOF = 19;
  public static final int IN = 54;
  public static final int OR = 26;
  public static final int COMMA = 60;
  public static final int BOOL = 9;
  public static final int ZERO = 2;
  public static final int IMPLIES = 28;
  public static final int CHILDREN = 23;
  public static final int GEQ = 37;
  public static final int CBRA = 63;
  public static final int PLUS = 39;
  public static final int MIN = 45;
  public static final int SQBRA = 58;
  public static final int THIS = 22;
  public static final int ID = 70;
  public static final int DOT = 65;
  public static final int EOF = 0;
  public static final int GROUP = 17;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int MUL = 47;
  public static final int INVERSEIMPLIES = 27;
  public static final int ORAGG = 51;
  public static final int ANDAGG = 50;
  public static final int AVG = 48;
  public static final int REAL = 4;
  public static final int TIMES = 42;
  public static final int COLON = 67;
  public static final int REALP = 13;
  public static final int ENUM = 11;
  public static final int SCHILDREN = 24;
  public static final int QUEST = 66;
  public static final int NOTEQUALS = 33;
  public static final int SQBRAEND = 59;
  public static final int LEQ = 38;
  public static final int SUM = 46;
  public static final int PARENT = 21;
  public static final int ROOT = 7;
  public static final int STRING = 5;
  public static final int OPT = 8;
  public static final int ONEOF = 18;
  public static final int BRA = 61;
  public static final int COUNT = 49;
  public static final int FALSE = 32;
  public static final int STRUCT = 12;
  public static final int MAX = 44;
  public static final int IFOUT = 15;
}

