/*
* generated by Xtext
*/
package fr.inria.familiar.fmlero.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FmleroAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/familiar/fmlero/parser/antlr/internal/InternalFmlero.tokens");
	}
}
