/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang;

import org.xtext.example.mydsl.idea.lang.AbstractFmlFileType;

@SuppressWarnings("all")
public class FmlFileType extends AbstractFmlFileType {
  public final static FmlFileType INSTANCE = new FmlFileType();
  
  public FmlFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(FmlLanguage) is undefined");
  }
}
