/*
 * generated by Xtext
 */
package fr.inria.familiar.fmlero;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FmleroRuntimeModule extends fr.inria.familiar.fmlero.AbstractFmleroRuntimeModule {

}
