/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFmlScopeProvider extends DelegatingScopeProvider {
}
