/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.xtext.example.mydsl.idea.lang.FmlLanguage;

public class FmlPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public FmlPomDeclarationSearcher() {
		super(FmlLanguage.INSTANCE);
	}
}
