<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fML" nsURI="http://www.xtext.org/example/mydsl/FML" nsPrefix="fML">
  <eClassifiers xsi:type="ecore:EClass" name="FamiliarScript">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmds" upperBound="-1" eType="#//ScriptCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exports" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaID" eType="#//StringExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexCommand" eSuperTypes="#//ScriptCommand #//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Command"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="batom" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//FMLAbstractCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerExpr" eSuperTypes="#//Command #//IntegerCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpr" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifierExpr" eSuperTypes="#//Command #//FMCommand #//FTCommand #//BCommand #//StrCommand #//ConfigurationCommand #//SetCommand #//ConstraintCommand #//IntegerCommand #//VariabilityOpCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaID" eType="#//StringExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpr" eSuperTypes="#//Command #//StrCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExpr" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" upperBound="-1" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicConstraintExpr" eSuperTypes="#//Command #//ConstraintCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//CNF" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintExpr" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//CNF" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EditConstant">
    <eLiterals name="REFACTORING" literal="REFACTORING"/>
    <eLiterals name="SPECIALIZATION" value="1" literal="SPECIALIZATION"/>
    <eLiterals name="GENERALIZATION" value="2" literal="GENERALIZATION"/>
    <eLiterals name="ARBITRARY" value="3" literal="ARBITRARY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureVariabilityOperator" eSuperTypes="#//Command #//VariabilityOpCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="#//FeatureEdgeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureEdgeKind">
    <eLiterals name="MANDATORY" literal="mand"/>
    <eLiterals name="OPTIONAL" value="1" literal="opt"/>
    <eLiterals name="ALTERNATIVE" value="2" literal="Xor"/>
    <eLiterals name="OR" value="3" literal="Or"/>
    <eLiterals name="MUTEX" value="4" literal="Mutex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfCondition" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bexpr" eType="#//ComplexCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" upperBound="-1" eType="#//ScriptCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" upperBound="-1" eType="#//ScriptCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeachSet" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" upperBound="-1"
        eType="#//ScriptCommand" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMLAbstractCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="FMCommand" eSuperTypes="#//FMLAbstractCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="FTCommand" eSuperTypes="#//FMLAbstractCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="BCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetCommand" eSuperTypes="#//FMLAbstractCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Leaves" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintCommand" eSuperTypes="#//FMLAbstractCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="GetConstraints" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfGet" eType="#//KindOfGet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KindOfGet">
    <eLiterals name="HIERARCHY_IMPLIES" literal="getImpliesHierarchy"/>
    <eLiterals name="HIERARCHY_EXCLUDES" value="1" literal="getExcludesHierarchy"/>
    <eLiterals name="HIERARCHY_BIIMPLIES" value="2" literal="getBiimpliesHierarchy"/>
    <eLiterals name="CONSTRAINT_IMPLIES" value="3" literal="getImpliesConstraint"/>
    <eLiterals name="CONSTRAINT_EXCLUDES" value="4" literal="getExcludesConstraint"/>
    <eLiterals name="CONSTRAINT_BIIMPLIES" value="5" literal="getBiimpliesConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputeConstraints" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfCompute" eType="#//KindOfCompute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="over" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fts" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KindOfCompute">
    <eLiterals name="IMPLIES" literal="computeImplies"/>
    <eLiterals name="EXCLUDES" value="1" literal="computeExcludes"/>
    <eLiterals name="BIIMPLIES" value="2" literal="computeBiimplies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetFGroups" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfGroups" eType="#//KindOfGetGroups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KindOfGetGroups">
    <eLiterals name="OR" literal="getORGroups"/>
    <eLiterals name="XOR" value="1" literal="getXORGroups"/>
    <eLiterals name="MUTEX" value="2" literal="getMUTEXGroups"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputeFGroups" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfGroups" eType="#//KindOfComputeGroups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KindOfComputeGroups">
    <eLiterals name="OR" literal="computeORGroups"/>
    <eLiterals name="XOR" value="1" literal="computeXORGroups"/>
    <eLiterals name="MUTEX" value="2" literal="computeMUTEXGroups"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PairwiseCommand" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimization" eType="#//IntegerCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partial" eType="#//IntegerCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleCommand" eSuperTypes="#//IntegerCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityOpCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisOperation" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetOperations" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetCard" eSuperTypes="#//IntegerCommand #//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetBelongs" eSuperTypes="#//BCommand #//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetUnionOrIntersection" eSuperTypes="#//SetCommand #//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setl" eType="#//SetCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setr" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetEmpty" eSuperTypes="#//SetCommand #//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetAddOrRemove" eSuperTypes="#//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setl" eType="#//SetCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Command"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsEmptySet" eSuperTypes="#//BCommand #//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetToNames" eSuperTypes="#//SetCommand #//SetOperations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureOperation" eSuperTypes="#//Command #//FTCommand #//StrCommand #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//FTCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AncestorFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescendantFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildrenFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SiblingFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMFeature" eSuperTypes="#//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringOperation" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringInit" eSuperTypes="#//StrCommand #//StringOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConcat" eSuperTypes="#//StrCommand #//StringOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstr" eType="#//StrCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rstr" eType="#//StrCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringSubstring" eSuperTypes="#//StrCommand #//StringOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="str" eType="#//StrCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begin" eType="#//IntegerCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//IntegerCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringIndexOf" eSuperTypes="#//IntegerCommand #//StringOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="str" eType="#//StrCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schar" eType="#//StrCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLength" eSuperTypes="#//IntegerCommand #//StringOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="str" eType="#//StrCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compare" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm_left" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm_right" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="param" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//lType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadGeneric" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stream" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="params" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTCRCommand" eSuperTypes="#//Command #//DoubleCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backend" eType="#//BDDBackend"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//MergeMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lfms" upperBound="-1" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fms" eType="#//LFMArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BDDBackend">
    <eLiterals name="BDD_DEFAULT" literal="@backend=DEFAULT"/>
    <eLiterals name="BDD_BASIC" value="1" literal="@backend=BDD"/>
    <eLiterals name="BDD_SPLOT" value="2" literal="@backend=BDD_SPLOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MergeMode">
    <eLiterals name="CROSS" literal="crossproduct"/>
    <eLiterals name="UNION" value="1" literal="union"/>
    <eLiterals name="SUNION" value="2" literal="sunion"/>
    <eLiterals name="INTER" value="3" literal="intersection"/>
    <eLiterals name="DIFF" value="4" literal="diff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LFMArgs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lfms" upperBound="-1" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateMerge" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchySpecified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchyStrategy" eType="#//HierarchyStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//MergeMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lfms" upperBound="-1" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fms" eType="#//LFMArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HierarchyStrategy">
    <eLiterals name="BASIC" literal="=basic"/>
    <eLiterals name="FLAT" value="1" literal="=flat"/>
    <eLiterals name="MST" value="2" literal="=mst"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synthesis" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kst" eType="#//KnowledgeSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchy" eType="#//HierarchySpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" eType="#//GroupsSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" eType="#//ConstraintsSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HierarchySpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchy" eType="#//Hierarchy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//HProduction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HProduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupsSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//GroupSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XorGroupSpec" eSuperTypes="#//GroupSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="MtxGroupSpec" eSuperTypes="#//GroupSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrGroupSpec" eSuperTypes="#//GroupSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintsSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="csts" eType="#//ConstraintExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slice" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//SliceMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fts" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SliceMode">
    <eLiterals name="INCLUDING" literal="including"/>
    <eLiterals name="EXCLUDING" value="1" literal="excluding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renamings" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fms" upperBound="-1" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sfms" eType="#//IdentifierExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModelOperation" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditOperation" eSuperTypes="#//FeatureModelOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Insert" eSuperTypes="#//BCommand #//FeatureModelOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspectfm" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseft" eType="#//FTCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//VariabilityOpCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveFeature" eSuperTypes="#//BCommand #//EditOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//FTCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenameFeature" eSuperTypes="#//BCommand #//EditOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//FTCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureNew" eType="#//StrCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extract" eSuperTypes="#//FMCommand #//FeatureModelOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootfeature" eType="#//FTCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertion" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
    <eLiterals name="EQUAL" literal="eq"/>
    <eLiterals name="NotEqual" value="1" literal="neq"/>
    <eLiterals name="LesserThan" value="2" literal="&lt;"/>
    <eLiterals name="GreaterThan" value="3" literal=">"/>
    <eLiterals name="REF_EQUAL" value="4" literal="=="/>
    <eLiterals name="REF_NotEqual" value="5" literal="!="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SetOperator">
    <eLiterals name="SUNION" literal="++"/>
    <eLiterals name="SDIFF" value="1" literal="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableNull" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Export">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//LVidentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hidden">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//LVidentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LVidentifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationCmd" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateConfiguration" eSuperTypes="#//ConfigurationCommand #//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompleteConfiguration" eSuperTypes="#//BCommand #//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//ConfigurationCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionFeature" eSuperTypes="#//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fts" upperBound="-1" eType="#//FeatureExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//ConfigurationCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ft" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpSelection">
    <eLiterals name="SELECT" literal="select"/>
    <eLiterals name="DESELECT" value="1" literal="deselect"/>
    <eLiterals name="UNSELECT" value="2" literal="unselect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoConfiguration" eSuperTypes="#//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//ConfigurationCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//AutoConfMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AutoConfMode">
    <eLiterals name="RANDOM" literal="RANDOM"/>
    <eLiterals name="MAX" value="1" literal="MAX"/>
    <eLiterals name="MIN" value="2" literal="MIN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectedConfiguration" eSuperTypes="#//SetCommand #//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//ConfigurationCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeselectedConfiguration" eSuperTypes="#//SetCommand #//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//ConfigurationCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnselectedConfiguration" eSuperTypes="#//ConfigurationCmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//ConfigurationCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsFM" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conf" eType="#//ConfigurationCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cst" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnMap" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CleanUp" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cores" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deads" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FullMandatorys" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cliques" eSuperTypes="#//Command #//SetCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptDefinition" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmds" upperBound="-1" eType="#//ScriptCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exports" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shell" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsConflicting" eSuperTypes="#//BCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Listing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opt" eType="#//OPT_LISTING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OPT_LISTING">
    <eLiterals name="NORMAL" literal="--normal"/>
    <eLiterals name="VERBOSE" value="1" literal="--verbose"/>
    <eLiterals name="VALUE_ONLY" value="2" literal="--withValues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyVariable" eSuperTypes="#//Command #//FMCommand #//FTCommand #//StrCommand #//VariabilityOpCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveVariable" eSuperTypes="#//Command #//BCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Convert" eSuperTypes="#//Command #//StrCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="v" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//FMFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FMFormat">
    <eLiterals name="DIMACS" literal="DIMACS"/>
    <eLiterals name="FMLBDD" value="1" literal="fmlbdd"/>
    <eLiterals name="FIDE" value="2" literal="featureide"/>
    <eLiterals name="FCALC" value="3" literal="fmcalc"/>
    <eLiterals name="FFML" value="4" literal="fml"/>
    <eLiterals name="FSPLOT" value="5" literal="SPLOT"/>
    <eLiterals name="FTVL" value="6" literal="TVL"/>
    <eLiterals name="FTRISKELL" value="7" literal="fd"/>
    <eLiterals name="FFML2" value="8" literal="xmi"/>
    <eLiterals name="S2T2" value="9" literal="S2T2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMLSave" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="v" eType="#//FMCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//FMFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hierarchy" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrinterUtility" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//LArgs" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LArgs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Command"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GDisplay" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdDisplay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GListing" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyVOperator" eSuperTypes="#//Command #//BCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryEdit" eSuperTypes="#//ModifyVOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ft" eType="#//FTCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalEdit" eSuperTypes="#//ModifyVOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ft" eType="#//FTCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeEdit" eSuperTypes="#//ModifyVOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fts" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrEdit" eSuperTypes="#//ModifyVOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fts" eType="#//SetCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddConstraint" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cst" eType="#//ConstraintCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveConstraint" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cst" eType="#//ConstraintCommand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fm" eType="#//FMCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CNF"/>
  <eClassifiers xsi:type="ecore:EClass" name="CNFExpression" eSuperTypes="#//CNF">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Neg_expr" eSuperTypes="#//CNFExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//CNFExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BOOL_Operator">
    <eLiterals name="BOOL_OR" literal="||"/>
    <eLiterals name="BOOL_AND" value="1" literal="&amp;&amp;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel" eSuperTypes="#//Command #//FMCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Production" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" upperBound="-1" eType="#//CNF"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="#//StringExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Production">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Child" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mandatory" eSuperTypes="#//Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional" eSuperTypes="#//Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Xorgroup" eSuperTypes="#//Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Orgroup" eSuperTypes="#//Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mutexgroup" eSuperTypes="#//Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerOperation" eSuperTypes="#//ComplexCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//IntegerCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolOperation" eSuperTypes="#//ComplexCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//BOOL_Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonOperation" eSuperTypes="#//ComplexCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmpOp" eType="#//ComparisonOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetOperation" eSuperTypes="#//ComplexCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sop" eType="#//SetOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//ComplexCommand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntLiteral" eSuperTypes="#//IntegerExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or_expr" eSuperTypes="#//CNFExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//CNFExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//CNFExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And_expr" eSuperTypes="#//CNFExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//CNFExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//CNFExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Impl_expr" eSuperTypes="#//CNFExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//CNFExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//CNFExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Biimpl_expr" eSuperTypes="#//CNFExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//CNFExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//CNFExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
