/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.fml.ConfigurationCmd;
import org.xtext.example.mydsl.fml.FmlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Configuration Cmd</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConfigurationCmdImpl extends CommandImpl implements ConfigurationCmd
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConfigurationCmdImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FmlPackage.eINSTANCE.getConfigurationCmd();
  }

} //ConfigurationCmdImpl
