/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.fml.FmlPackage;
import org.xtext.example.mydsl.fml.IntegerCommand;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integer Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntegerCommandImpl extends MinimalEObjectImpl.Container implements IntegerCommand
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegerCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FmlPackage.eINSTANCE.getIntegerCommand();
  }

} //IntegerCommandImpl
