/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.fml.FmlPackage;
import org.xtext.example.mydsl.fml.IntegerExpr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integer Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntegerExprImpl extends CommandImpl implements IntegerExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegerExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FmlPackage.eINSTANCE.getIntegerExpr();
  }

} //IntegerExprImpl
