/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.fml.FmlPackage;
import org.xtext.example.mydsl.fml.MtxGroupSpec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mtx Group Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MtxGroupSpecImpl extends GroupSpecImpl implements MtxGroupSpec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MtxGroupSpecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FmlPackage.eINSTANCE.getMtxGroupSpec();
  }

} //MtxGroupSpecImpl
