/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.fml.FmlPackage;
import org.xtext.example.mydsl.fml.SetCommand;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Set Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SetCommandImpl extends FMLAbstractCommandImpl implements SetCommand
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FmlPackage.eINSTANCE.getSetCommand();
  }

} //SetCommandImpl
