/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.fml.FmlPackage;
import org.xtext.example.mydsl.fml.SetOperations;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Set Operations</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SetOperationsImpl extends CommandImpl implements SetOperations
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetOperationsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FmlPackage.eINSTANCE.getSetOperations();
  }

} //SetOperationsImpl
