/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.xtext.example.mydsl.idea.lang.FmlFileType;
import org.xtext.example.mydsl.idea.lang.FmlLanguage;

public final class FmlFileImpl extends BaseXtextFile {

	public FmlFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, FmlLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return FmlFileType.INSTANCE;
	}
}
