/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.completion;

import org.xtext.example.mydsl.idea.completion.AbstractFmlCompletionContributor;

@SuppressWarnings("all")
public class FmlCompletionContributor extends AbstractFmlCompletionContributor {
  public FmlCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor FmlCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public FmlCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
