/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractFmlFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "fml";

	protected AbstractFmlFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "Fml files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "Fml";
	}

}
