/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class FmlFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(FmlFileType.INSTANCE, AbstractFmlFileType.DEFAULT_EXTENSION);
	}

}
