/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class FmlLanguage extends AbstractXtextLanguage {

	public static final FmlLanguage INSTANCE = new FmlLanguage();

	private FmlLanguage() {
		super("org.xtext.example.mydsl.Fml");
	}

}
