/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>As FM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.fml.AsFM#getConf <em>Conf</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getAsFM()
 * @model
 * @generated
 */
public interface AsFM extends Command, FMCommand
{
  /**
   * Returns the value of the '<em><b>Conf</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conf</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conf</em>' containment reference.
   * @see #setConf(ConfigurationCommand)
   * @see org.xtext.example.mydsl.fml.FmlPackage#getAsFM_Conf()
   * @model containment="true"
   * @generated
   */
  ConfigurationCommand getConf();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fml.AsFM#getConf <em>Conf</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conf</em>' containment reference.
   * @see #getConf()
   * @generated
   */
  void setConf(ConfigurationCommand value);

} // AsFM
