/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Constraint Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.fml.AtomicConstraintExpr#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getAtomicConstraintExpr()
 * @model
 * @generated
 */
public interface AtomicConstraintExpr extends Command, ConstraintCommand
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(CNF)
   * @see org.xtext.example.mydsl.fml.FmlPackage#getAtomicConstraintExpr_Expr()
   * @model containment="true"
   * @generated
   */
  CNF getExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fml.AtomicConstraintExpr#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(CNF value);

} // AtomicConstraintExpr
