/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edit Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getEditOperation()
 * @model
 * @generated
 */
public interface EditOperation extends FeatureModelOperation
{
} // EditOperation
