/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Model Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getFeatureModelOperation()
 * @model
 * @generated
 */
public interface FeatureModelOperation extends Command
{
} // FeatureModelOperation
