/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getIntegerExpr()
 * @model
 * @generated
 */
public interface IntegerExpr extends Command, IntegerCommand
{
} // IntegerExpr
