/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.fml.Merge#getBackend <em>Backend</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.fml.Merge#isLazy <em>Lazy</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.fml.Merge#getMode <em>Mode</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.fml.Merge#getLfms <em>Lfms</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.fml.Merge#getFms <em>Fms</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getMerge()
 * @model
 * @generated
 */
public interface Merge extends Command, FMCommand
{
  /**
   * Returns the value of the '<em><b>Backend</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.fml.BDDBackend}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Backend</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Backend</em>' attribute.
   * @see org.xtext.example.mydsl.fml.BDDBackend
   * @see #setBackend(BDDBackend)
   * @see org.xtext.example.mydsl.fml.FmlPackage#getMerge_Backend()
   * @model
   * @generated
   */
  BDDBackend getBackend();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fml.Merge#getBackend <em>Backend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Backend</em>' attribute.
   * @see org.xtext.example.mydsl.fml.BDDBackend
   * @see #getBackend()
   * @generated
   */
  void setBackend(BDDBackend value);

  /**
   * Returns the value of the '<em><b>Lazy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lazy</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lazy</em>' attribute.
   * @see #setLazy(boolean)
   * @see org.xtext.example.mydsl.fml.FmlPackage#getMerge_Lazy()
   * @model
   * @generated
   */
  boolean isLazy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fml.Merge#isLazy <em>Lazy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lazy</em>' attribute.
   * @see #isLazy()
   * @generated
   */
  void setLazy(boolean value);

  /**
   * Returns the value of the '<em><b>Mode</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.fml.MergeMode}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mode</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' attribute.
   * @see org.xtext.example.mydsl.fml.MergeMode
   * @see #setMode(MergeMode)
   * @see org.xtext.example.mydsl.fml.FmlPackage#getMerge_Mode()
   * @model
   * @generated
   */
  MergeMode getMode();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fml.Merge#getMode <em>Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' attribute.
   * @see org.xtext.example.mydsl.fml.MergeMode
   * @see #getMode()
   * @generated
   */
  void setMode(MergeMode value);

  /**
   * Returns the value of the '<em><b>Lfms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.fml.FMCommand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lfms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lfms</em>' containment reference list.
   * @see org.xtext.example.mydsl.fml.FmlPackage#getMerge_Lfms()
   * @model containment="true"
   * @generated
   */
  EList<FMCommand> getLfms();

  /**
   * Returns the value of the '<em><b>Fms</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fms</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fms</em>' containment reference.
   * @see #setFms(LFMArgs)
   * @see org.xtext.example.mydsl.fml.FmlPackage#getMerge_Fms()
   * @model containment="true"
   * @generated
   */
  LFMArgs getFms();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fml.Merge#getFms <em>Fms</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fms</em>' containment reference.
   * @see #getFms()
   * @generated
   */
  void setFms(LFMArgs value);

} // Merge
