/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modify VOperator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getModifyVOperator()
 * @model
 * @generated
 */
public interface ModifyVOperator extends Command, BCommand
{
} // ModifyVOperator
