/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Or Group Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getOrGroupSpec()
 * @model
 * @generated
 */
public interface OrGroupSpec extends GroupSpec
{
} // OrGroupSpec
