/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.fml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.fml.FmlPackage#getSetCommand()
 * @model
 * @generated
 */
public interface SetCommand extends FMLAbstractCommand
{
} // SetCommand
