/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.highlighting;

import org.xtext.example.mydsl.idea.highlighting.FmlBaseColorSettingsPage;

@SuppressWarnings("all")
public class FmlColorSettingsPage extends FmlBaseColorSettingsPage {
}
