/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl.ui.AbstractFmlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FmlUiModule extends AbstractFmlUiModule {
  public FmlUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
