/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.fml.ui.internal.FmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FmlActivator.getInstance().getInjector(FmlActivator.ORG_XTEXT_EXAMPLE_MYDSL_FML);
	}
	
}
