/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalFmlParser;
import org.xtext.example.mydsl.services.FmlGrammarAccess;

public class FmlParser extends AbstractAntlrParser {

	@Inject
	private FmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFmlParser createParser(XtextTokenStream stream) {
		return new InternalFmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FamiliarScript";
	}

	public FmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
