/*
* generated by Xtext
*/
package fr.inria.familiar.fmlero.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class FmleroProposalProvider extends fr.inria.familiar.fmlero.ui.contentassist.AbstractFmleroProposalProvider {

}
