/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FmlUiModule extends AbstractFmlUiModule {
}
