/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.xtext.example.mydsl.idea.lang.FmlLanguage;

public class FmlFacetType extends AbstractFacetType<FmlFacetConfiguration> {

	public static final FacetTypeId<Facet<FmlFacetConfiguration>> TYPEID = new FacetTypeId<Facet<FmlFacetConfiguration>>("org.xtext.example.mydsl.Fml");

	public FmlFacetType() {
		super(TYPEID, "org.xtext.example.mydsl.Fml", "Fml");
		FmlLanguage.INSTANCE.injectMembers(this);
	}
}
