/*
 * generated by Xtext
 */
package fr.inria.familiar.fmlero.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.familiar.fmlero.ui.internal.FmleroActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FmleroExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FmleroActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FmleroActivator.getInstance().getInjector(FmleroActivator.FR_INRIA_FAMILIAR_FMLERO_FMLERO);
	}
	
}
