/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractFmlCompletionContributor extends TerminalsCompletionContributor {
	public AbstractFmlCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
