/*
* generated by Xtext
*/
package fr.inria.familiar.fmlero.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractFmleroJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.inria.familiar.fmlero.fmprimitives.FmprimitivesPackage.eINSTANCE);
		return result;
	}

}
